# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_calibration_v01.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(912, 736)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/rc/resources/applogo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_3.addWidget(self.line)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblCurrentInstrument = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrentInstrument.setObjectName("lblCurrentInstrument")
        self.horizontalLayout_3.addWidget(self.lblCurrentInstrument)
        self.lblCurrentCalibration = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrentCalibration.setObjectName("lblCurrentCalibration")
        self.horizontalLayout_3.addWidget(self.lblCurrentCalibration)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.lblLogo = QtWidgets.QLabel(self.centralwidget)
        self.lblLogo.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lblLogo.setText("")
        self.lblLogo.setPixmap(QtGui.QPixmap(":/rc/resources/mtlogo.png"))
        self.lblLogo.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLogo.setObjectName("lblLogo")
        self.horizontalLayout.addWidget(self.lblLogo)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setLineWidth(2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_2.addWidget(self.line_4)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_2.addWidget(self.label_7)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout_2.addWidget(self.line_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 1, 1, 1)
        self.lblCurrTestTestpointInfo = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrTestTestpointInfo.setObjectName("lblCurrTestTestpointInfo")
        self.gridLayout_2.addWidget(self.lblCurrTestTestpointInfo, 2, 0, 1, 1)
        self.lblCurrTestProcessingInstr = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrTestProcessingInstr.setObjectName("lblCurrTestProcessingInstr")
        self.gridLayout_2.addWidget(self.lblCurrTestProcessingInstr, 2, 1, 1, 1)
        self.lblCurrTestSpecs = QtWidgets.QLabel(self.centralwidget)
        self.lblCurrTestSpecs.setObjectName("lblCurrTestSpecs")
        self.gridLayout_2.addWidget(self.lblCurrTestSpecs, 2, 2, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.lblLastMeasurmentResult = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lblLastMeasurmentResult.setFont(font)
        self.lblLastMeasurmentResult.setObjectName("lblLastMeasurmentResult")
        self.verticalLayout.addWidget(self.lblLastMeasurmentResult)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setLineWidth(2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_2.addWidget(self.line_5)
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_2.addWidget(self.label_9)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lblSelectedTestTestpointInfo = QtWidgets.QLabel(self.centralwidget)
        self.lblSelectedTestTestpointInfo.setObjectName("lblSelectedTestTestpointInfo")
        self.gridLayout.addWidget(self.lblSelectedTestTestpointInfo, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 0, 1, 1)
        self.treeVwTestpoints = QtWidgets.QTreeView(self.centralwidget)
        self.treeVwTestpoints.setMinimumSize(QtCore.QSize(320, 0))
        self.treeVwTestpoints.setMaximumSize(QtCore.QSize(500, 16777215))
        self.treeVwTestpoints.setObjectName("treeVwTestpoints")
        self.gridLayout.addWidget(self.treeVwTestpoints, 2, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 1, 1, 1)
        self.line_7 = QtWidgets.QFrame(self.centralwidget)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout.addWidget(self.line_7, 1, 0, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.centralwidget)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.gridLayout.addWidget(self.line_8, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_4.addWidget(self.label_12)
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout_4.addWidget(self.line_6)
        self.lblSelectedTestMeasurementsDone = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Courier")
        self.lblSelectedTestMeasurementsDone.setFont(font)
        self.lblSelectedTestMeasurementsDone.setObjectName("lblSelectedTestMeasurementsDone")
        self.verticalLayout_4.addWidget(self.lblSelectedTestMeasurementsDone)
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 912, 36))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        self.menuTools = QtWidgets.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionLoad_Test_Sequence_Data = QtWidgets.QAction(MainWindow)
        self.actionLoad_Test_Sequence_Data.setObjectName("actionLoad_Test_Sequence_Data")
        self.actionSelect_Calibration = QtWidgets.QAction(MainWindow)
        self.actionSelect_Calibration.setEnabled(False)
        self.actionSelect_Calibration.setObjectName("actionSelect_Calibration")
        self.actionStart_Measurements = QtWidgets.QAction(MainWindow)
        self.actionStart_Measurements.setObjectName("actionStart_Measurements")
        self.actionNext_without_Save = QtWidgets.QAction(MainWindow)
        self.actionNext_without_Save.setObjectName("actionNext_without_Save")
        self.actionPause_before_Save = QtWidgets.QAction(MainWindow)
        self.actionPause_before_Save.setCheckable(True)
        self.actionPause_before_Save.setChecked(False)
        self.actionPause_before_Save.setObjectName("actionPause_before_Save")
        self.actionContinue_with_Save = QtWidgets.QAction(MainWindow)
        self.actionContinue_with_Save.setObjectName("actionContinue_with_Save")
        self.actionRepeat = QtWidgets.QAction(MainWindow)
        self.actionRepeat.setObjectName("actionRepeat")
        self.actionSelect_Instrument = QtWidgets.QAction(MainWindow)
        self.actionSelect_Instrument.setEnabled(False)
        self.actionSelect_Instrument.setObjectName("actionSelect_Instrument")
        self.actionReport_only = QtWidgets.QAction(MainWindow)
        self.actionReport_only.setObjectName("actionReport_only")
        self.actionSynchronize = QtWidgets.QAction(MainWindow)
        self.actionSynchronize.setObjectName("actionSynchronize")
        self.menuFile.addAction(self.actionLoad_Test_Sequence_Data)
        self.menuFile.addAction(self.actionSelect_Instrument)
        self.menuFile.addAction(self.actionSelect_Calibration)
        self.menuRun.addAction(self.actionStart_Measurements)
        self.menuRun.addAction(self.actionPause_before_Save)
        self.menuRun.addAction(self.actionContinue_with_Save)
        self.menuRun.addAction(self.actionNext_without_Save)
        self.menuRun.addAction(self.actionRepeat)
        self.menuTools.addAction(self.actionSynchronize)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())
        self.toolBar.addAction(self.actionLoad_Test_Sequence_Data)
        self.toolBar.addAction(self.actionSelect_Instrument)
        self.toolBar.addAction(self.actionSelect_Calibration)
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionStart_Measurements)
        self.toolBar.addAction(self.actionPause_before_Save)
        self.toolBar.addAction(self.actionNext_without_Save)
        self.toolBar.addAction(self.actionContinue_with_Save)
        self.toolBar.addAction(self.actionRepeat)
        self.toolBar.addSeparator()

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scheidt MessTechnik Calibration"))
        self.label_4.setText(_translate("MainWindow", "Information about important setting"))
        self.lblCurrentInstrument.setText(_translate("MainWindow", "no Instrument selected"))
        self.lblCurrentCalibration.setText(_translate("MainWindow", "no Calibration selected"))
        self.label_7.setText(_translate("MainWindow", "Information about current or next test. Current if test ist runing:"))
        self.label_2.setText(_translate("MainWindow", "Current/Next Testpoint"))
        self.label.setText(_translate("MainWindow", "Current/Next Sepcification"))
        self.label_3.setText(_translate("MainWindow", "Current/Next Processing Instructions"))
        self.lblCurrTestTestpointInfo.setText(_translate("MainWindow", "TextLabel"))
        self.lblCurrTestProcessingInstr.setText(_translate("MainWindow", "TextLabel"))
        self.lblCurrTestSpecs.setText(_translate("MainWindow", "TextLabel"))
        self.label_5.setText(_translate("MainWindow", "Result of latest measurement"))
        self.lblLastMeasurmentResult.setText(_translate("MainWindow", "TextLabel"))
        self.label_9.setText(_translate("MainWindow", "Information about loaded test sequence:"))
        self.lblSelectedTestTestpointInfo.setText(_translate("MainWindow", "Current testpoint"))
        self.label_10.setText(_translate("MainWindow", "Structure of loaded test sequence"))
        self.label_11.setText(_translate("MainWindow", "Information on selected test:"))
        self.label_12.setText(_translate("MainWindow", "Results of Measurments already done for selected test"))
        self.lblSelectedTestMeasurementsDone.setText(_translate("MainWindow", "TextLabel"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.menuTools.setTitle(_translate("MainWindow", "Tools"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionLoad_Test_Sequence_Data.setText(_translate("MainWindow", "Load Test Sequence Data"))
        self.actionLoad_Test_Sequence_Data.setToolTip(_translate("MainWindow", "Load Test Sequence Data"))
        self.actionSelect_Calibration.setText(_translate("MainWindow", "Select Calibration"))
        self.actionStart_Measurements.setText(_translate("MainWindow", "Start Measurements"))
        self.actionStart_Measurements.setToolTip(_translate("MainWindow", "Starts a complete calibration"))
        self.actionStart_Measurements.setShortcut(_translate("MainWindow", "F5"))
        self.actionNext_without_Save.setText(_translate("MainWindow", "Next without Save"))
        self.actionPause_before_Save.setText(_translate("MainWindow", "Pause before Save"))
        self.actionContinue_with_Save.setText(_translate("MainWindow", "Continue with Save"))
        self.actionRepeat.setText(_translate("MainWindow", "Repeat"))
        self.actionSelect_Instrument.setText(_translate("MainWindow", "Select Instrument"))
        self.actionReport_only.setText(_translate("MainWindow", "Report only"))
        self.actionSynchronize.setText(_translate("MainWindow", "Synchronize"))


import smt_cal_demo.calibration.guis.main_ui.main_calibration_rc_v01_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
