# -*- coding: utf-8 -*-
"""
Created on Fri Dec 28 14:21:27 2012

@author: Scheidt
"""

C = "C"
Ohm = "Ohm"
S = "S"
F = "F"
V = "V"
A = "A"
Hz = "Hz"
s = "s"
H = "H"
W = "W"
GradC = "°C"
K = "K"
rad = "rad"
scalar = "scalar"
scalar_per_cent = "scalar_per_cent"
scalar_one_to_one = "scalar_one_to_one"
scalar_ppm = "scalar_ppm"
scalar_ratio_one_over = "scalar_ratio_one_over"
V_per_A = "V_per_A"
A_per_V = "A_per_V"
V_per_div = "V_per_div"
none = "none"
Ohm_per_Ohm = "Ohm/Ohm"
Ohm_per_s = "Ohm/s"
Ohm_per_K = "Ohm/K"
TypeDesc = "Type"
string = "string"